<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>

<body>
    <!-- <nav>
        <ul>
            <?php foreach (CONFIG_ROUTES as $key => $value) : ?>
                <li>
                    <a href='?page=<?php echo $key ?>'> <?php echo $key ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </nav> -->

<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">MVC PHP🐘</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a class="mr-5 hover:text-gray-900" href="?page=home">Home</a>
      <a class="mr-5 hover:text-gray-900" href="?page=gallery">Gallery</a>
      <a class="mr-5 hover:text-gray-900" href="?page=contact">Contact</a>
    </nav>

  </div>
</header>

    <?php include "./views/".'template_'.$page.'.phtml'; ?>

</body>

</html>