<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>

<body>
    <nav>
        <ul>
            <?php foreach (CONFIG_ROUTES as $key => $value) : ?>
                <li>
                    <a href='?page=<?php echo $key ?>'> <?php echo $key ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </nav>

    <?php include "./views/".'template_'.$page.'.phtml'; ?>

</body>

</html>